name: Dependabot Automerge
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
jobs:
  merge:
    uses: rubykatzen/releaser/.github/workflows/dependabot-automerge-shared.yml@v0.3.1
    secrets: inherit
