name: Lint
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: rubykatzen/baseline/.github/actions/lint-yamllint@v0.5.2
      - uses: rubykatzen/baseline/.github/actions/lint-pymarkdown@v0.5.2
      - uses: rubykatzen/baseline/.github/actions/lint-actionlint@v0.5.2
