name: Telegram Release Notify
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  notify:
    uses: rubykatzen/releaser/.github/workflows/notify-telegram-unreleased-shared.yml@v0.5
    secrets: inherit
