name: Release
on:
  push:
    tags:
      - "v*"
concurrency:
  group: release-homebrew-tap
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: rubykatzen/baseline/.github/actions/create-release@v0.5.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
