name: Telegram Release Notify
on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:
jobs:
  notify:
    uses: rubykatzen/releaser/.github/workflows/telegram-release-notify-shared.yml@v0.3.2
    secrets: inherit
