name: Update Formulas
"on":
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  actions: write
concurrency:
  group: update-homebrew-formulas
  cancel-in-progress: false
jobs:
  update:
    uses: rubykatzen/releaser/.github/workflows/update-homebrew-formulas-shared.yml@v0.5.10
    with:
      auto_merge: true
      workflows_dispatch: lint
